export const en = {
    dir: '', // stands for the direction of the language set in the head, defaults to LTR (left to right)
    skipToContent: 'Skip to Content',
    availableLang: 'This page is also available in:',
    langOptions: 'Language Options:',
    mainNav: 'Main',
    footerNav: 'Footer',
    welcome: 'Welcome to ',
    latestPosts: 'Latest Posts',
    published: 'Published:',
    updated: 'Last Updated:',
    author: 'Author:',
    toc: 'In This Article',
    replyByEmail: 'Reply by Email',
    emailReplySubject: 'RE: ',
    nextPrev: 'Next and Previous Posts',
    rssFeed: 'RSS Feed',
    emailContact: 'Contact me by email',
    plaintxtEmail: '(<a href="https://useplaintext.email/">Plain text email</a> encouraged)',
    sourceCode: 'Source Code',
    socialNav: 'Socials',
    backToTop: 'Back to Top'
};

export const zh = {
    skipToContent: '跳至内容区',
    availableLang: '此页面也有此语言版本:',
    langOptions: '语言选项:',
    mainNav: '主要',
    footerNav: '页脚',
    welcome: '欢迎光临',
    latestPosts: '最新文章',
    published: '发布:',
    updated: '最后更新:',
    author: '作者:',
    toc: '本文中',
    replyByEmail: '电邮回复',
    emailReplySubject: '回复：',
    nextPrev: '上一篇和下一篇文章',
    rssFeed: 'RSS 订阅',
    emailContact: '电子邮件联系我',
    plaintxtEmail: '（鼓励使用<a href="https://useplaintext.email/">纯文本电邮</a>）',
    sourceCode: '源代码',
    socialNav: '社交媒体',
    backToTop: '返回顶端'
};