export const en = {
	dir: '', // stands for the direction of the language set in the head, defaults to LTR (left to right)
	skipToContent: 'Skip to Content',
	availableLang: 'View this page in: ',
	langOptions: 'Language Options:',
	translations: 'Translations',
	mainNav: 'Main',
	footerNav: 'Footer',
	siteBadgeAlt: "88-by-31 badge: Galaxy Garden's logo, a light yellow minimalist shape of a galaxy resembling the capital G, next to the word Galaxy Garden on a dark purple background.",
	welcome: 'Welcome to ',
	webDirectories: 'Web Directories',
	directoryDesc: ' is listed at the following directories:',
	latestPosts: 'Latest Posts',
	published: 'Published:',
	updated: 'Last Updated:',
	author: 'Author:',
	topics: 'Topics:',
	postLang: 'Languages: ',
	pageToC: 'On This Page',
	postToC: 'In This Article',
	replyByEmail: 'Reply by Email',
	emailReplySubject: 'RE: ',
	nextPrev: 'Next and Previous Posts',
	prevPost: 'Previous Post:',
	nextPost: 'Next Post:',
	rssFeed: 'RSS Feed',
	emailContact: 'Contact me by email',
	plaintxtEmail: '(<a href="https://useplaintext.email/">Plain text email</a> encouraged)',
	sourceCode: 'Source Code',
	socialNav: 'Socials',
	backToTop: 'Back to Top'
};

export const zh = {
	skipToContent: '跳至内容区',
	availableLang: '切换本页语言:',
	langOptions: '语言选项:',
	translations: '翻译',
	mainNav: '主要',
	footerNav: '页脚',
	siteBadgeAlt: "88 × 31 网页徽章： 银河花园的徽标——一个浅黄色、样子与大写字母 G 相似的简约的银河形状，旁边是 Galaxy Garden 字样，背景为深紫色。",
	welcome: '欢迎光临',
	webDirectories: '网站目录',
	directoryDesc: '被列入以下目录：',
	latestPosts: '最新文章',
	published: '发布:',
	updated: '最后更新:',
	author: '作者:',
	topics: '话题: ',
	postLang: '语言: ',
	pageToC: '本页中',
	postToC: '本文中',
	replyByEmail: '电邮回复',
	emailReplySubject: '回复：',
	nextPrev: '上一篇和下一篇文章',
	prevPost: '上一篇文章：',
	nextPost: '下一篇文章：',
	rssFeed: 'RSS 订阅',
	emailContact: '电子邮件联系我',
	plaintxtEmail: '（鼓励使用<a href="https://useplaintext.email/">纯文本电邮</a>）',
	sourceCode: '源代码',
	socialNav: '社交媒体',
	backToTop: '返回顶端'
};
